spring:
   application:
     name: Department-Test
   datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/department
     username: root
     password: root
   jpa:
     hibernate:
      ddl-auto: update
     properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect
server:
   port: 9001


---